// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pinklet.data;

#nullable disable

namespace pinklet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pinklet.Models.Cake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cake3dModelLink")
                        .HasColumnType("text");

                    b.Property<string>("CakeCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CakeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CakeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CakeImageLink1")
                        .HasColumnType("text");

                    b.Property<string>("CakeImageLink2")
                        .HasColumnType("text");

                    b.Property<string>("CakeImageLink3")
                        .HasColumnType("text");

                    b.Property<string>("CakeImageLink4")
                        .HasColumnType("text");

                    b.Property<string>("CakeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CakePrice")
                        .HasColumnType("double precision");

                    b.Property<int>("CakeRating")
                        .HasColumnType("integer");

                    b.Property<string>("CakeTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cakes");
                });

            modelBuilder.Entity("pinklet.Models.CakeLayerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CakeId")
                        .HasColumnType("integer");

                    b.Property<string>("LayerColorizeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerFlavor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerGradientColor1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerGradientColor2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerGradientDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerHeight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LayerNo")
                        .HasColumnType("integer");

                    b.Property<string>("LayerPatternBGColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerPatternColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerPatternType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerSoidColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CakeId");

                    b.ToTable("CakeLayers");
                });

            modelBuilder.Entity("pinklet.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("boolean");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("pinklet.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemImageLink1")
                        .HasColumnType("text");

                    b.Property<string>("ItemImageLink2")
                        .HasColumnType("text");

                    b.Property<string>("ItemImageLink3")
                        .HasColumnType("text");

                    b.Property<string>("ItemImageLink4")
                        .HasColumnType("text");

                    b.Property<string>("ItemImageLink5")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ItemPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("ItemRating")
                        .HasColumnType("integer");

                    b.Property<int>("ItemStock")
                        .HasColumnType("integer");

                    b.Property<string>("ItemSubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("pinklet.Models.ItemPackage", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ItemId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("ItemPackages");
                });

            modelBuilder.Entity("pinklet.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CakeId")
                        .HasColumnType("integer");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ThreeDCakeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("_3DCakeModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CakeId");

                    b.HasIndex("ThreeDCakeId");

                    b.HasIndex("UserId");

                    b.HasIndex("_3DCakeModelId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("pinklet.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageLink")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pinklet.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IDImageLink1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IDImageLink2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ShopCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShopCoverImageLink")
                        .HasColumnType("text");

                    b.Property<string>("ShopDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShopDistrict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShopProfileImageLink")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("pinklet.Models._3DCakeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseShapeSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CakeCode")
                        .HasColumnType("text");

                    b.Property<string>("IcingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsReqested")
                        .HasColumnType("boolean");

                    b.Property<string>("LayerShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NoLayers")
                        .HasColumnType("integer");

                    b.Property<string>("Occation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("RequestedPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Toppers")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cakes3dModel");
                });

            modelBuilder.Entity("pinklet.Models.CakeLayerModel", b =>
                {
                    b.HasOne("pinklet.Models._3DCakeModel", "Cake")
                        .WithMany("CakeLayers")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cake");
                });

            modelBuilder.Entity("pinklet.Models.Cart", b =>
                {
                    b.HasOne("pinklet.Models.Package", "Package")
                        .WithOne("Cart")
                        .HasForeignKey("pinklet.Models.Cart", "PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pinklet.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("pinklet.Models.Item", b =>
                {
                    b.HasOne("pinklet.Models.User", "Vendor")
                        .WithMany("Items")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("pinklet.Models.ItemPackage", b =>
                {
                    b.HasOne("pinklet.Models.Item", "Item")
                        .WithMany("ItemPackages")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pinklet.Models.Package", "Package")
                        .WithMany("ItemPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("pinklet.Models.Package", b =>
                {
                    b.HasOne("pinklet.Models.Cake", "Cake")
                        .WithMany("Packages")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("pinklet.Models._3DCakeModel", "ThreeDCake")
                        .WithMany()
                        .HasForeignKey("ThreeDCakeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("pinklet.Models.User", "User")
                        .WithMany("Packages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pinklet.Models._3DCakeModel", null)
                        .WithMany("Packages")
                        .HasForeignKey("_3DCakeModelId");

                    b.Navigation("Cake");

                    b.Navigation("ThreeDCake");

                    b.Navigation("User");
                });

            modelBuilder.Entity("pinklet.Models.Vendor", b =>
                {
                    b.HasOne("pinklet.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("pinklet.Models.Vendor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("pinklet.Models.Cake", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("pinklet.Models.Item", b =>
                {
                    b.Navigation("ItemPackages");
                });

            modelBuilder.Entity("pinklet.Models.Package", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("ItemPackages");
                });

            modelBuilder.Entity("pinklet.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Items");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("pinklet.Models._3DCakeModel", b =>
                {
                    b.Navigation("CakeLayers");

                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
